# Generated by Django 3.0.4 on 2024-05-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('product_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Manufacture')),
            ],
        ),
    ]
