# Generated by Django 3.0.4 on 2024-05-13 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=254, null=True)),
                ('name', models.CharField(max_length=254, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 5, 13, 18, 38, 11, 401646))),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
